import asyncio
import json
import time
import re
import random
import os
from urllib.parse import urlparse, parse_qs
from typing import Dict, Any

from rich.console import Console
from rich.prompt import Prompt, IntPrompt
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn

# Environment variable loading
try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# OpenAI imports for Vercel AI Gateway
from openai import AsyncOpenAI

# Mitmproxy imports
from mitmproxy import http
from mitmproxy import options
from mitmproxy.tools.dump import DumpMaster

# Playwright imports
from playwright.async_api import async_playwright

console = Console()

class APISpecBuilder:
    """Intelligently builds an OpenAPI 3.0 spec from captured HTTP traffic."""
    def __init__(self, base_url: str):
        parsed = urlparse(base_url)
        self.openapi = {
            "openapi": "3.0.0",
            "info": {
                "title": "Auto-Generated API Spec",
                "version": "1.0.0",
                "description": f"Automatically generated by API Auto-Discover. Target: {base_url}"
            },
            "servers": [{"url": f"{parsed.scheme}://{parsed.netloc}"}],
            "paths": {}
        }
        self.target_netloc = parsed.netloc
        # Capture the base domain to include subdomains (like api.domain.com)
        self.target_base = self.target_netloc.replace("www.", "")

    def _infer_schema(self, data: Any) -> Dict[str, Any]:
        """Recursively infers JSON schema from python objects."""
        if isinstance(data, dict):
            properties = {}
            for k, v in data.items():
                properties[k] = self._infer_schema(v)
            return {"type": "object", "properties": properties}
        elif isinstance(data, list):
            items = self._infer_schema(data[0]) if data else {}
            return {"type": "array", "items": items}
        elif isinstance(data, bool):
            return {"type": "boolean"}
        elif isinstance(data, int):
            return {"type": "integer"}
        elif isinstance(data, float):
            return {"type": "number"}
        else:
            return {"type": "string"}

    def _generalize_path(self, path: str) -> str:
        """Replaces numeric path segments with {id} for grouping."""
        return re.sub(r'/(\d+)(/|$)', r'/{id}\2', path)

    def process_flow(self, flow: http.HTTPFlow):
        """Processes a single mitmproxy flow and updates the OpenAPI spec."""
        req = flow.request
        res = flow.response

        # Only process requests targeting our main domain (or subdomains) and returning JSON
        if self.target_base not in req.host:
            return
        
        content_type = res.headers.get("Content-Type", "").lower()
        if "json" not in content_type:
            return

        method = req.method.lower()
        parsed_url = urlparse(req.path)
        raw_path = parsed_url.path
        
        # Skip static asset noise that might accidentally be labeled json
        if raw_path.endswith(('.js', '.css', '.png', '.jpg')): 
            return

        path = self._generalize_path(raw_path)

        if path not in self.openapi["paths"]:
            self.openapi["paths"][path] = {}

        if method not in self.openapi["paths"][path]:
            self.openapi["paths"][path][method] = {
                "summary": f"Auto-generated {method.upper()} for {path}",
                "responses": {},
                "parameters": []
            }

        operation = self.openapi["paths"][path][method]

        # Extract Query Parameters
        if parsed_url.query:
            query_params = parse_qs(parsed_url.query)
            for param_name in query_params:
                # Check if param already exists
                if not any(p.get("name") == param_name for p in operation["parameters"]):
                    operation["parameters"].append({
                        "name": param_name,
                        "in": "query",
                        "schema": {"type": "string"}
                    })

        # Process Request Body Schema
        if req.content and "json" in req.headers.get("Content-Type", "").lower():
            try:
                req_json = json.loads(req.content)
                operation["requestBody"] = {
                    "content": {
                        "application/json": {
                            "schema": self._infer_schema(req_json)
                        }
                    }
                }
            except Exception:
                pass

        # Process Response Schema
        status_code = str(res.status_code)
        if status_code not in operation["responses"]:
            operation["responses"][status_code] = {"description": "Auto-captured response"}
            
            if res.content:
                try:
                    res_json = json.loads(res.content)
                    operation["responses"][status_code]["content"] = {
                        "application/json": {
                            "schema": self._infer_schema(res_json)
                        }
                    }
                except Exception:
                    pass

    def save(self, filename: str = "openapi_spec.json"):
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(self.openapi, f, indent=2)


class APICaptureAddon:
    """Mitmproxy Addon that hooks into HTTP responses."""
    def __init__(self, spec_builder: APISpecBuilder, capture_callback):
        self.spec_builder = spec_builder
        self.capture_callback = capture_callback

    def response(self, flow: http.HTTPFlow):
        # Update spec internally
        self.spec_builder.process_flow(flow)
        
        # Trigger UI update if it was an API call to the target (or its subdomains)
        if self.spec_builder.target_base in flow.request.host:
            if "json" in flow.response.headers.get("Content-Type", "").lower():
                self.capture_callback(flow.request.method, flow.request.path)


async def run_crawler(url: str, duration: int, proxy_port: int, progress_task, progress):
    """Uses Playwright to navigate the site automatically."""
    proxy_server = f"http://127.0.0.1:{proxy_port}"
    
    async with async_playwright() as p:
        # Launch Chromium routing traffic through our mitmproxy instance
        # ignore-certificate-errors is required to bypass the mitmproxy CA validation
        browser = await p.chromium.launch(
            headless=True,
            proxy={"server": proxy_server},
            args=["--ignore-certificate-errors"]
        )
        context = await browser.new_context(ignore_https_errors=True)
        page = await context.new_page()

        visited_urls = set()
        queue = [url]
        start_time = time.time()
        
        try:
            while (time.time() - start_time) < duration:
                # Update progress bar
                elapsed = time.time() - start_time
                progress.update(progress_task, completed=elapsed)
                
                if not queue:
                    # If queue is empty, refresh the main page to find new dynamic content
                    queue.append(url)
                    await asyncio.sleep(2)

                current_url = queue.pop(0)
                if current_url in visited_urls:
                    continue
                    
                visited_urls.add(current_url)
                
                try:
                    await page.goto(current_url, wait_until="networkidle", timeout=15000)
                    
                    # Random actions to trigger APIs (click random buttons, scroll)
                    await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                    await asyncio.sleep(1) # Let lazy loading trigger
                    
                    # Try interacting with a few buttons to trigger dynamic SPA requests
                    try:
                        buttons = await page.locator("button, [role='button']").all()
                        for btn in random.sample(buttons, min(len(buttons), 3)):
                            await btn.click(timeout=1000, no_wait_after=True)
                            await asyncio.sleep(0.5)
                    except Exception:
                        pass
                    
                    # Extract same-origin links to continue crawling
                    hrefs = await page.evaluate(r"""() => {
                        return Array.from(document.querySelectorAll('a'))
                            .map(a => a.href)
                            .filter(href => href.startsWith(window.location.origin));
                    }""")
                    
                    for href in hrefs:
                        if href not in visited_urls and href not in queue:
                            queue.append(href)
                            
                except Exception:
                    # Ignore timeouts or navigation errors on specific links
                    pass
                
        finally:
            await browser.close()
            # Complete the progress bar
        progress.update(progress_task, completed=duration)


async def generate_ai_documentation(spec_data: dict, target_url: str):
    """Uses Vercel AI Gateway with xAI Grok to generate documentation."""
    console.print()
    console.print(Panel.fit(
        "[bold cyan]AI Documentation Generation[/bold cyan]\n"
        "We can now use Vercel AI Gateway and [bold]xai/grok-4.1-fast-reasoning[/bold]\n"
        "to write usage documentation for the discovered endpoints.",
        border_style="cyan"
    ))
    
    # Try to load from .env.local file
    if load_dotenv:
        load_dotenv(".env.local")
        
    api_key = os.getenv("VERCEL_AI_API_KEY")
    
    if api_key:
        console.print("[green]API Key automatically loaded from environment / .env.local[/green]")
    else:
        api_key = Prompt.ask("[bold cyan]Enter your Vercel AI Gateway API Key (or press enter to skip)[/bold cyan]", password=True)
        
    if not api_key:
        console.print("[yellow]Skipping AI documentation generation.[/yellow]")
        return

    console.print("[cyan]Generating documentation using xai/grok-4.1-fast-reasoning... This may take a minute.[/cyan]")
    
    try:
        # Vercel AI Gateway uses the standard OpenAI client format
        client = AsyncOpenAI(
            api_key=api_key,
            base_url="https://ai-gateway.vercel.sh/v1"
        )
        
        prompt = f"""
        You are an expert technical writer. Please generate a comprehensive Markdown documentation file 
        for the following automatically discovered API from {target_url}. 
        
        For each endpoint, include:
        1. A brief, plain-English explanation of what it likely does.
        2. A clear usage example using Python (requests library).
        3. A clear usage example using JavaScript (fetch API).
        
        Please ensure all content remains educational, safe, and professional.

        OpenAPI Spec:
        {json.dumps(spec_data, indent=2)}
        """

        response = await client.chat.completions.create(
            model="xai/grok-4.1-fast-reasoning",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3
        )
        
        doc_content = response.choices[0].message.content
        with open("api_documentation.md", "w", encoding="utf-8") as f:
            f.write(doc_content)
            
        console.print(f"\n[bold green]✅ AI Documentation successfully generated: api_documentation.md[/bold green]")
        
    except Exception as e:
        console.print(f"\n[bold red]❌ Failed to generate documentation:[/bold red] {e}")


async def main():
    console.print(Panel.fit(
        "[bold red]⚠️ DISCLAIMER: For Educational and Authorized Testing Purposes Only ⚠️[/bold red]\n"
        "[white]This tool captures and maps network traffic automatically.\n"
        "Do not use it against systems or networks for which you do not have explicit permission.[/white]",
        title="API Auto-Discover Tool", border_style="red"
    ))

    target_url = Prompt.ask("[bold cyan]Enter the Target URL to crawl[/bold cyan]", default="https://example.com")
    duration = IntPrompt.ask("[bold cyan]Enter crawling duration in seconds[/bold cyan]", default=30)
    proxy_port = 8080

    spec_builder = APISpecBuilder(target_url)

    captured_endpoints = 0
    
    def on_api_captured(method, path):
        nonlocal captured_endpoints
        captured_endpoints += 1

    console.print(f"\n[green]Starting Mitmproxy on port {proxy_port}...[/green]")
    
    # Configure Mitmproxy
    opts = options.Options(listen_host='127.0.0.1', listen_port=proxy_port)
    master = DumpMaster(opts, with_termlog=False, with_dumper=False)
    master.addons.add(APICaptureAddon(spec_builder, on_api_captured))
    
    # Run proxy as an asyncio background task
    proxy_task = asyncio.create_task(master.run())
    
    console.print(f"[green]Starting Playwright Crawler for {duration} seconds...[/green]\n")

    # Set up Rich progress bar
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        
        crawl_task_id = progress.add_task("[cyan]Crawling & Capturing...", total=duration)
        
        # Start crawling
        await run_crawler(target_url, duration, proxy_port, crawl_task_id, progress)

    console.print("\n[yellow]Shutting down proxy server...[/yellow]")
    master.shutdown()
    await proxy_task

    # Save outputs
    output_file = "openapi_spec.json"
    spec_builder.save(output_file)
    
    console.print(Panel.fit(
        f"[bold green]✅ Crawl Complete![/bold green]\n"
        f"Captured API Endpoints: [bold yellow]{captured_endpoints}[/bold yellow]\n"
        f"OpenAPI Spec generated: [bold cyan]{output_file}[/bold cyan]\n",
        border_style="green"
    ))

    # Trigger the AI documentation generation if endpoints were found
    if captured_endpoints > 0:
        await generate_ai_documentation(spec_builder.openapi, target_url)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        console.print("\n[bold red]Operation cancelled by user.[/bold red]")